### ISSUE TITLE
``mpld3.show()`` fails in Python 3.4

### ISSUE THREAD

**Issue by jakevdp** [mpld3/mpld3#196]
Error is the same as seen here: http://stackoverflow.com/questions/11781639/typeerror-str-does-not-support-buffer-interface

The solution is to encode the string in Python 3.

This was not caught by unit tests, because I'm not sure how to unit test the launch of an HTTP server.

**Comment by MichaelCurrie** [comment]
Are we sure this is fixed?  I just tried using mpld3 for the first time using the example in [Quick Start](https://mpld3.github.io/quickstart.html):

```
import matplotlib.pyplot as plt, mpld3
plt.plot([3,1,4,1,5], 'ks-', mec='w', mew=5, ms=20)
mpld3.show()
```

 and I get this error:

```
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> runfile('C:/Users/Michael/Dropbox/INBOX/mpld3 test.py', wdir='C:/Users/Michael/Dropbox/INBOX')
Serving to http://127.0.0.1:8889/    [Ctrl-C to exit]
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 61380)
----------------------------------------
127.0.0.1 - - [28/Jun/2015 15:56:18] "GET / HTTP/1.1" 200 -
Traceback (most recent call last):
  File "C:\WinPython\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\lib\socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\WinPython\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\lib\socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "C:\WinPython\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\lib\socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\WinPython\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\lib\socketserver.py", line 673, in __init__
    self.handle()
  File "C:\WinPython\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\lib\http\server.py", line 398, in handle
    self.handle_one_request()
  File "C:\WinPython\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\lib\http\server.py", line 386, in handle_one_request
    method()
  File "C:\WinPython\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\lib\site-packages\mpld3\_server.py", line 38, in do_GET
    self.wfile.write("<html><head>"
  File "C:\WinPython\WinPython-64bit-3.4.3.3\python-3.4.3.amd64\lib\socket.py", line 394, in write
    return self._sock.send(b)
TypeError: 'str' does not support the buffer interface
```

Using the usual matplotlib backend works fine:

```
import matplotlib.pyplot as plt, mpld3
plt.plot([3,1,4,1,5], 'ks-', mec='w', mew=5, ms=20)
plt.show()
```

**Comment by jakevdp** [comment]
Did you install mpld3 from master? This fix isn't in a release yet (sorry)

**Comment by MichaelCurrie** [comment]
No I installed using `pip install mpld3` as instructed in the [install guide](http://mpld3.github.io/install.html#installing-released-versions).  As you suggest I'll install from master for now.

Thanks for your great work on this project, I look forward to using it in [my project](https://github.com/openworm/movement_validation/issues/91).

**Comment by jakevdp** [comment]
We should absolutely create a new release.
