### ISSUE TITLE
Minimal test plot crashes

### ISSUE THREAD

**Issue by mwiebusch78** [mpld3/mpld3#356]
I copied the following minimal test code from the web page:

    import matplotlib.pyplot as plt, mpld3
    plt.plot([3,1,4,1,5], 'ks-', mec='w', mew=5, ms=20)
    mpld3.show()

This crashes on my computer with the following Traceback:

    Serving to http://127.0.0.1:8888/    [Ctrl-C to exit]
    127.0.0.1 - - [22/Apr/2016 17:01:56] "GET / HTTP/1.1" 200 -
    ----------------------------------------
    Exception happened during processing of request from ('127.0.0.1', 57805)
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.4/socketserver.py", line 305, in _handle_request_noblock
        self.process_request(request, client_address)
      File "/opt/anaconda3/lib/python3.4/socketserver.py", line 331, in process_request
        self.finish_request(request, client_address)
      File "/opt/anaconda3/lib/python3.4/socketserver.py", line 344, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "/opt/anaconda3/lib/python3.4/socketserver.py", line 673, in __init__
        self.handle()
      File "/opt/anaconda3/lib/python3.4/http/server.py", line 398, in handle
        self.handle_one_request()
      File "/opt/anaconda3/lib/python3.4/http/server.py", line 386, in handle_one_request
        method()
      File "/opt/anaconda3/lib/python3.4/site-packages/mpld3/_server.py", line 38, in do_GET
        self.wfile.write("<html><head>"
      File "/opt/anaconda3/lib/python3.4/socket.py", line 394, in write
        return self._sock.send(b)
    TypeError: 'str' does not support the buffer interface
    ----------------------------------------

I'm using a mac.

**Comment by aflaxman** [comment]
maybe a python 3.4 issue?  patches most definitely welcome!

**Comment by jakevdp** [comment]
This is a known bug in the released version; ``show()`` doesn't work for Python 3. It's been fixed in master.
