### ISSUE TITLE
notebook conversion fails for mpld3.github.io build

### ISSUE THREAD

**Issue by etgalloway** [mpld3/mpld3#401]
The Sphinx build of [mpld3.github.io](http://mpld3.github.io/) fails for the [notebook examples](http://mpld3.github.io/notebooks/index.html#notebook-examples).

This is for Python 2.7.

The traceback:
```bash
# Sphinx version: 1.4.8
# Python version: 2.7.12 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/ericgalloway/miniconda3/envs/py27/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/ericgalloway/miniconda3/envs/py27/lib/python2.7/site-packages/sphinx/application.py", line 204, in __init__
    self._init_builder(self.buildername)
  File "/home/ericgalloway/miniconda3/envs/py27/lib/python2.7/site-packages/sphinx/application.py", line 279, in _init_builder
    self.emit('builder-inited')
  File "/home/ericgalloway/miniconda3/envs/py27/lib/python2.7/site-packages/sphinx/application.py", line 551, in emit
    results.append(callback(self, *args))
  File "/home/ericgalloway/repos/mpld3/mpld3/doc/sphinxext/notebook_converter.py", line 87, in main
    (body, resources) = exporter.from_notebook_node(nb_json)
  File "/home/ericgalloway/miniconda3/envs/py27/lib/python2.7/site-packages/nbconvert/exporters/html.py", line 65, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/ericgalloway/miniconda3/envs/py27/lib/python2.7/site-packages/nbconvert/exporters/templateexporter.py", line 200, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/ericgalloway/miniconda3/envs/py27/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 130, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/ericgalloway/miniconda3/envs/py27/lib/python2.7/site-packages/nbconvert/exporters/exporter.py", line 302, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/ericgalloway/miniconda3/envs/py27/lib/python2.7/site-packages/nbconvert/preprocessors/coalescestreams.py", line 29, in wrappedfunc
    for index, cell in enumerate(nb.cells):
  File "/home/ericgalloway/miniconda3/envs/py27/lib/python2.7/site-packages/ipython_genutils/ipstruct.py", line 134, in __getattr__
    raise AttributeError(key)
AttributeError: cells
```

**Comment by etgalloway** [comment]
Closed by #403.
