### ISSUE TITLE
Matplotlib 3.2.1 seems to not work

### ISSUE THREAD

**Issue by vladh** [mpld3/mpld3#465]
```
python setup.py buildjs && python visualize_tests.py
```

```
________________________________________________________________________________
test_contour.py is not compiling:
Traceback (most recent call last):
  File "visualize_tests.py", line 140, in execute_file
    {'plt': plt, 'mpld3': mpld3, '__name__': '__main__'})
  File "<string>", line 29, in <module>
  File "<string>", line 12, in create_plot
AttributeError: module 'matplotlib.mlab' has no attribute 'bivariate_normal'
________________________________________________________________________________
Traceback (most recent call last):
  File "visualize_tests.py", line 275, in <module>
    outfile, nolaunch = run_main()
  File "visualize_tests.py", line 270, in run_main
    mpld3_url=args.mpld3_url)
  File "visualize_tests.py", line 197, in combine_testplots
    fig_png.extend(result.iter_png())
  File "visualize_tests.py", line 155, in iter_png
    for fig in self.figlist:
AttributeError: 'ExecFile' object has no attribute 'figlist'
```

We probably just need to take out `bivariate_normal`. I remember already having fixed this on some branch?

**Comment by cliffckerr** [comment]
Hopefully just a broken test rather than broken code!
