### ISSUE TITLE
KeyError: 'gridOn' 出现了这个问题，应该怎么解决呢？

### ISSUE THREAD

**Issue by nba20416** [mpld3/mpld3#500]
Traceback (most recent call last):
  File "D:/3D/pyecharts_draw_3D/keshihua/keshihua/points_mian.py", line 110, in <module>
    html_str = mpld3.fig_to_html(fig)
  File "D:\Anaconda\envs\Atlains\lib\site-packages\mpld3\_display.py", line 250, in fig_to_html
    Exporter(renderer, close_mpl=False, **kwargs).run(fig)
  File "D:\Anaconda\envs\Atlains\lib\site-packages\mpld3\mplexporter\exporter.py", line 51, in run
    self.crawl_fig(fig)
  File "D:\Anaconda\envs\Atlains\lib\site-packages\mpld3\mplexporter\exporter.py", line 118, in crawl_fig
    self.crawl_ax(ax)
  File "D:\Anaconda\envs\Atlains\lib\site-packages\mpld3\mplexporter\exporter.py", line 123, in crawl_ax
    props=utils.get_axes_properties(ax)):
  File "D:\Anaconda\envs\Atlains\lib\site-packages\mpld3\mplexporter\utils.py", line 289, in get_axes_properties
    'axes': [get_axis_properties(ax.xaxis),
  File "D:\Anaconda\envs\Atlains\lib\site-packages\mpld3\mplexporter\utils.py", line 253, in get_axis_properties
    props['grid'] = get_grid_style(axis)
  File "D:\Anaconda\envs\Atlains\lib\site-packages\mpld3\mplexporter\utils.py", line 263, in get_grid_style
    if axis._major_tick_kw['gridOn'] and len(gridlines) > 0:
KeyError: 'gridOn'

**Comment by vladh** [comment]
I'm sorry, but I can only help you if you describe your issue in English (or Japanese or German). Feel free to reopen another ticket if you're able to do this!
